<?php

if($npcc ==1){
echo "<META HTTP-EQUIV=REFRESH CONTENT='0;URL=HTTPS://QR.ALIPAY.COM/FKX00229CZSWJDGJSBDO8B'>";

} elseif($npcc ==2){
echo "<META HTTP-EQUIV=REFRESH CONTENT='0;URL=HTTPS://QR.ALIPAY.COM/FKX01310M27LVYWMPYCEB5'>";

} elseif($npcc ==3){
echo "<META HTTP-EQUIV=REFRESH CONTENT='0;URL=HTTPS://QR.ALIPAY.COM/FKX06890AYSAKT2CKVJ3CC'>";

} elseif($npcc ==4){
echo "<META HTTP-EQUIV=REFRESH CONTENT='0;URL=HTTPS://QR.ALIPAY.COM/FKX03797QBWAHJDOBFKNB2'>";


} elseif($npcc ==5){
echo "<META HTTP-EQUIV=REFRESH CONTENT='0;URL=HTTPS://QR.ALIPAY.COM/FKX08556BDIBLK9BGD7H03'>";


} else{
	
	
	
} 


?>